version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    depends_on:
      - db
    environment:
       DATABASE_URL: db
       DATABASE_USERNAME: postgres
       DATABASE_PASSWORD: admin

  db:
    image: 'postgres:13.1-alpine'
    ports:
      - 5432:5432
    environment:
       POSTGRES_USER: postgres
       POSTGRES_PASSWORD: admin
       POSTGRES_DB: preloved